# Generated by Django 6.0.1 on 2026-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('data_evento', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('tipo_evento', models.CharField(help_text='Ex: Aniversário, Corporativo', max_length=100, verbose_name='Tipo de Evento')),
                ('numero_pessoas', models.IntegerField(verbose_name='Nº de Pessoas')),
                ('telefone_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Análise'), ('CONFIRMADO', 'Reserva Confirmada'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Evento Realizado')], default='PENDENTE', max_length=20)),
                ('valor_acertado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total (R$)')),
                ('local_giardini', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local Definido')),
                ('tema_decoracao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tema da Decoração')),
                ('coffee_break', models.TextField(blank=True, null=True, verbose_name='Itens do Coffee Break')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
